version: '3.7'
networks:
  devnet:
    external: true


services:
  mysql:
    image: couchbase
    container_name: mysql
    networks:
      - devnet
    ports:
      - 8091-8094:8091-8094
      - 11210:11210
      - 30173:11210
      - 31760:8091
    volumes:
      - ./data/mysql:/opt/couchbase/var
